sudo: required

services:
  - Docker

before_install:
  - docker build -t uppalavijay/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run uppalavijay/react-test npm test  -- --coverage

after_success:
  - docker build -t uppalavijay/muilti-client ./client
  - docker build -t uppalavijay/muilti-ngnix ./ngnix
  - docker build -t uppalavijay/muilti-server ./server
  - docker build -t uppalavijay/muilti-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  - docker push uppalavijay/muilti-client
  - docker push uppalavijay/muilti-ngnix
  - docker push uppalavijay/muilti-server
  - docker push uppalavijay/muilti-worker